import type { EstimadorConfig } from "./types";

/**
 * Config por defecto del modelo de estimación.
 * Se usa como fallback si la tabla `estimador_config` está vacía.
 * Desde el panel de admin se puede sobrescribir (modificar / sumar / quitar coeficientes).
 */
export const DEFAULT_CONFIG: EstimadorConfig = {
  superficieDescubiertaFactor: 0.35,
  topeMin: 0.55,
  topeMax: 1.6,
  rango: { alta: 0.05, media: 0.08, baja: 0.12 },
  factores: [
    {
      id: "superficie_cubierta",
      label: "Superficie cubierta",
      tipo: "rango",
      input: "m2Cubiertos",
      activo: true,
      rangos: [
        { max: 30, coef: 1.10, label: "Hasta 30 m²" },
        { min: 31, max: 50, coef: 1.05, label: "31 a 50 m²" },
        { min: 51, max: 100, coef: 1.00, label: "51 a 100 m²" },
        { min: 101, max: 150, coef: 0.95, label: "101 a 150 m²" },
        { min: 151, coef: 0.90, label: "Más de 150 m²" },
      ],
    },
    {
      id: "piso",
      label: "Piso",
      tipo: "rango",
      input: "piso",
      activo: true,
      rangos: [
        { max: 0, coef: 0.90, label: "Planta baja" },
        { min: 1, max: 3, coef: 0.95, label: "1° a 3° piso" },
        { min: 4, max: 5, coef: 1.00, label: "4° a 5° piso" },
        { min: 6, max: 8, coef: 1.10, label: "6° a 8° piso" },
        { min: 9, coef: 1.15, label: "9° piso o superior" },
      ],
    },
    {
      id: "ultimo_piso",
      label: "Último piso",
      tipo: "booleano",
      input: "ultimoPiso",
      activo: true,
      coefTrue: 0.90,
      coefFalse: 1.00,
    },
    {
      id: "categoria",
      label: "Categoría del edificio",
      tipo: "opcion",
      input: "categoria",
      activo: true,
      opciones: {
        regular: { coef: 0.90, label: "Regular" },
        estandar: { coef: 1.00, label: "Estándar" },
        premium: { coef: 1.25, label: "Premium" },
      },
    },
    {
      id: "estado",
      label: "Estado de conservación",
      tipo: "opcion",
      input: "estado",
      activo: true,
      opciones: {
        a_reciclar: { coef: 0.88, label: "A reciclar" },
        bueno: { coef: 1.00, label: "Bueno" },
        muy_bueno: { coef: 1.08, label: "Muy bueno" },
        a_estrenar: { coef: 1.15, label: "A estrenar" },
      },
    },
    {
      id: "antiguedad",
      label: "Antigüedad",
      tipo: "rango",
      input: "antiguedad",
      activo: true,
      rangos: [
        { max: 5, coef: 1.05, label: "Hasta 5 años" },
        { min: 6, max: 15, coef: 1.02, label: "6 a 15 años" },
        { min: 16, max: 30, coef: 1.00, label: "16 a 30 años" },
        { min: 31, max: 50, coef: 0.95, label: "31 a 50 años" },
        { min: 51, coef: 0.90, label: "Más de 50 años" },
      ],
    },
    {
      id: "disposicion",
      label: "Disposición",
      tipo: "opcion",
      input: "disposicion",
      activo: true,
      opciones: {
        frente: { coef: 1.03, label: "Frente" },
        contrafrente: { coef: 0.97, label: "Contrafrente" },
        interno: { coef: 0.94, label: "Interno" },
      },
    },
    {
      id: "orientacion",
      label: "Orientación",
      tipo: "opcion",
      input: "orientacion",
      activo: true,
      opciones: {
        norte: { coef: 1.02, label: "Norte" },
        noreste: { coef: 1.02, label: "Noreste" },
        noroeste: { coef: 1.02, label: "Noroeste" },
        este: { coef: 1.01, label: "Este" },
        oeste: { coef: 1.01, label: "Oeste" },
        sur: { coef: 0.98, label: "Sur" },
        sureste: { coef: 0.98, label: "Sureste" },
        suroeste: { coef: 0.98, label: "Suroeste" },
      },
    },
    {
      id: "cochera",
      label: "Cochera",
      tipo: "booleano",
      input: "cochera",
      activo: true,
      coefTrue: 1.07,
      coefFalse: 1.00,
    },
    {
      id: "baulera",
      label: "Baulera",
      tipo: "booleano",
      input: "baulera",
      activo: true,
      coefTrue: 1.02,
      coefFalse: 1.00,
    },
    {
      id: "amenity_pileta",
      label: "Piscina",
      tipo: "booleano",
      input: "amenities.pileta",
      activo: true,
      coefTrue: 1.03,
      coefFalse: 1.00,
    },
    {
      id: "amenity_gimnasio",
      label: "Gimnasio",
      tipo: "booleano",
      input: "amenities.gimnasio",
      activo: true,
      coefTrue: 1.02,
      coefFalse: 1.00,
    },
    {
      id: "amenity_seguridad",
      label: "Seguridad",
      tipo: "booleano",
      input: "amenities.seguridad",
      activo: true,
      coefTrue: 1.02,
      coefFalse: 1.00,
    },
    {
      id: "amenity_sum",
      label: "SUM",
      tipo: "booleano",
      input: "amenities.sum",
      activo: true,
      coefTrue: 1.015,
      coefFalse: 1.00,
    },
    {
      id: "amenity_parrilla",
      label: "Parrilla",
      tipo: "booleano",
      input: "amenities.parrilla",
      activo: true,
      coefTrue: 1.01,
      coefFalse: 1.00,
    },
    {
      id: "banos",
      label: "Baños",
      tipo: "rango",
      input: "banos",
      activo: true,
      rangos: [
        { max: 1, coef: 1.00, label: "1 baño" },
        { min: 2, max: 2, coef: 1.025, label: "2 baños" },
        { min: 3, coef: 1.05, label: "3 o más baños" },
      ],
    },
  ],
};
