import type { EstimadorConfig } from "./types";

/**
 * Config por defecto del modelo de estimación (v2).
 * Si la versión guardada en la DB difiere de esta, se migra a este default.
 * Desde el panel de admin se puede sobrescribir (modificar / sumar / quitar coeficientes).
 */
export const DEFAULT_CONFIG: EstimadorConfig = {
  version: 2,
  superficieSemicubiertaFactor: 0.5,
  superficieDescubiertaFactor: 0.3,
  estadoObra: { usado: 1.0, a_estrenar: 1.28, pozo: 1.18 },
  topeMin: 0.5,
  topeMax: 1.55,
  rango: { alta: 0.05, media: 0.08, baja: 0.12 },
  factores: [
    {
      id: "superficie_cubierta",
      label: "Superficie cubierta",
      tipo: "rango",
      input: "m2Cubiertos",
      activo: true,
      rangos: [
        { max: 30, coef: 1.10, label: "Hasta 30 m²" },
        { min: 31, max: 50, coef: 1.05, label: "31 a 50 m²" },
        { min: 51, max: 100, coef: 1.00, label: "51 a 100 m²" },
        { min: 101, max: 150, coef: 0.95, label: "101 a 150 m²" },
        { min: 151, coef: 0.90, label: "Más de 150 m²" },
      ],
    },
    {
      id: "tipologia",
      label: "Tipología (liquidez)",
      tipo: "rango",
      input: "ambientes",
      activo: true,
      rangos: [
        { max: 1, coef: 0.99, label: "Monoambiente" },
        { min: 2, max: 2, coef: 1.02, label: "2 ambientes" },
        { min: 3, max: 3, coef: 1.01, label: "3 ambientes" },
        { min: 4, max: 4, coef: 0.99, label: "4 ambientes" },
        { min: 5, coef: 0.97, label: "5 o más ambientes" },
      ],
    },
    {
      id: "piso",
      label: "Piso",
      tipo: "rango",
      input: "piso",
      activo: true,
      rangos: [
        { max: 0, coef: 0.90, label: "Planta baja" },
        { min: 1, max: 3, coef: 0.95, label: "1° a 3° piso" },
        { min: 4, max: 5, coef: 1.00, label: "4° a 5° piso" },
        { min: 6, max: 8, coef: 1.10, label: "6° a 8° piso" },
        { min: 9, coef: 1.15, label: "9° piso o superior" },
      ],
    },
    {
      id: "ascensor",
      label: "Ascensor",
      tipo: "booleano",
      input: "ascensor",
      activo: true,
      coefTrue: 1.00,
      coefFalse: 0.94,
    },
    {
      id: "ultimo_piso",
      label: "Último piso",
      tipo: "booleano",
      input: "ultimoPiso",
      activo: true,
      coefTrue: 0.95,
      coefFalse: 1.00,
    },
    {
      id: "categoria",
      label: "Categoría del edificio",
      tipo: "opcion",
      input: "categoria",
      activo: true,
      opciones: {
        regular: { coef: 0.90, label: "Regular" },
        estandar: { coef: 1.00, label: "Estándar" },
        premium: { coef: 1.25, label: "Premium" },
      },
    },
    {
      id: "estado",
      label: "Estado de conservación",
      tipo: "opcion",
      input: "estado",
      activo: true,
      opciones: {
        a_reciclar: { coef: 0.85, label: "A reciclar" },
        bueno: { coef: 1.00, label: "Bueno" },
        muy_bueno: { coef: 1.06, label: "Muy bueno" },
        excelente: { coef: 1.12, label: "Excelente" },
      },
    },
    {
      id: "antiguedad",
      label: "Antigüedad",
      tipo: "rango",
      input: "antiguedad",
      activo: true,
      rangos: [
        { max: 5, coef: 1.03, label: "Hasta 5 años" },
        { min: 6, max: 15, coef: 1.01, label: "6 a 15 años" },
        { min: 16, max: 30, coef: 1.00, label: "16 a 30 años" },
        { min: 31, max: 50, coef: 0.96, label: "31 a 50 años" },
        { min: 51, coef: 0.91, label: "Más de 50 años" },
      ],
    },
    {
      id: "disposicion",
      label: "Disposición",
      tipo: "opcion",
      input: "disposicion",
      activo: true,
      opciones: {
        frente: { coef: 1.03, label: "Frente" },
        contrafrente: { coef: 0.97, label: "Contrafrente" },
        interno: { coef: 0.94, label: "Interno" },
      },
    },
    {
      id: "vista",
      label: "Vista",
      tipo: "opcion",
      input: "vista",
      activo: true,
      opciones: {
        abierta: { coef: 1.06, label: "Abierta / panorámica" },
        despejada: { coef: 1.03, label: "Despejada" },
        a_la_calle: { coef: 1.00, label: "A la calle" },
        interna: { coef: 0.97, label: "Interna / pulmón" },
      },
    },
    {
      id: "orientacion",
      label: "Orientación",
      tipo: "opcion",
      input: "orientacion",
      activo: true,
      opciones: {
        norte: { coef: 1.02, label: "Norte" },
        noreste: { coef: 1.02, label: "Noreste" },
        noroeste: { coef: 1.02, label: "Noroeste" },
        este: { coef: 1.01, label: "Este" },
        oeste: { coef: 1.01, label: "Oeste" },
        sur: { coef: 0.98, label: "Sur" },
        sureste: { coef: 0.98, label: "Sureste" },
        suroeste: { coef: 0.98, label: "Suroeste" },
      },
    },
    {
      id: "cochera",
      label: "Cochera",
      tipo: "opcion",
      input: "cochera",
      activo: true,
      opciones: {
        no: { coef: 1.00, label: "Sin cochera" },
        descubierta: { coef: 1.04, label: "Descubierta" },
        movil: { coef: 1.05, label: "Cubierta móvil" },
        fija: { coef: 1.08, label: "Cubierta fija" },
      },
    },
    {
      id: "baulera",
      label: "Baulera",
      tipo: "booleano",
      input: "baulera",
      activo: true,
      coefTrue: 1.02,
      coefFalse: 1.00,
    },
    {
      id: "dependencia_servicio",
      label: "Dependencia de servicio",
      tipo: "booleano",
      input: "dependenciaServicio",
      activo: true,
      coefTrue: 1.03,
      coefFalse: 1.00,
    },
    {
      id: "calefaccion",
      label: "Calefacción",
      tipo: "opcion",
      input: "calefaccion",
      activo: true,
      opciones: {
        losa: { coef: 1.03, label: "Losa radiante" },
        central: { coef: 1.02, label: "Central" },
        individual: { coef: 1.00, label: "Individual" },
        sin: { coef: 0.97, label: "Sin calefacción" },
      },
    },
    {
      id: "expensas",
      label: "Expensas",
      tipo: "opcion",
      input: "expensas",
      activo: true,
      opciones: {
        bajas: { coef: 1.02, label: "Bajas" },
        medias: { coef: 1.00, label: "Medias" },
        altas: { coef: 0.96, label: "Altas" },
      },
    },
    {
      id: "apto_credito",
      label: "Apto crédito hipotecario",
      tipo: "booleano",
      input: "aptoCredito",
      activo: true,
      coefTrue: 1.04,
      coefFalse: 1.00,
    },
    {
      id: "ocupacion",
      label: "Ocupación",
      tipo: "opcion",
      input: "ocupacion",
      activo: true,
      opciones: {
        libre: { coef: 1.00, label: "Libre" },
        alquilada: { coef: 0.95, label: "Alquilada" },
        ocupada: { coef: 0.88, label: "Ocupada" },
      },
    },
    {
      id: "situacion_dominial",
      label: "Situación dominial",
      tipo: "opcion",
      input: "situacionDominial",
      activo: true,
      opciones: {
        escritura: { coef: 1.00, label: "Escritura al día" },
        sucesion: { coef: 0.95, label: "En sucesión" },
        observaciones: { coef: 0.92, label: "Con observaciones" },
      },
    },
    {
      id: "vecinos_especiales",
      label: "Vecinos especiales",
      tipo: "booleano",
      input: "vecinosEspeciales",
      activo: true,
      coefTrue: 0.93,
      coefFalse: 1.00,
    },
    {
      id: "amenity_pileta",
      label: "Piscina",
      tipo: "booleano",
      input: "amenities.pileta",
      activo: true,
      coefTrue: 1.03,
      coefFalse: 1.00,
    },
    {
      id: "amenity_gimnasio",
      label: "Gimnasio",
      tipo: "booleano",
      input: "amenities.gimnasio",
      activo: true,
      coefTrue: 1.02,
      coefFalse: 1.00,
    },
    {
      id: "amenity_seguridad",
      label: "Seguridad",
      tipo: "booleano",
      input: "amenities.seguridad",
      activo: true,
      coefTrue: 1.02,
      coefFalse: 1.00,
    },
    {
      id: "amenity_sum",
      label: "SUM",
      tipo: "booleano",
      input: "amenities.sum",
      activo: true,
      coefTrue: 1.015,
      coefFalse: 1.00,
    },
    {
      id: "amenity_parrilla",
      label: "Parrilla",
      tipo: "booleano",
      input: "amenities.parrilla",
      activo: true,
      coefTrue: 1.01,
      coefFalse: 1.00,
    },
    {
      id: "banos",
      label: "Baños",
      tipo: "rango",
      input: "banos",
      activo: true,
      rangos: [
        { max: 1, coef: 1.00, label: "1 baño" },
        { min: 2, max: 2, coef: 1.025, label: "2 baños" },
        { min: 3, coef: 1.05, label: "3 o más baños" },
      ],
    },
  ],
};
