export const ZONAS = [
  "Ciudad Autónoma de Buenos Aires",
  "Provincia de Buenos Aires",
] as const;

export type Zona = (typeof ZONAS)[number];

export const BARRIOS_CABA: string[] = [
  "Agronomía",
  "Almagro",
  "Balvanera",
  "Barracas",
  "Belgrano",
  "Boedo",
  "Caballito",
  "Chacarita",
  "Coghlan",
  "Colegiales",
  "Constitución",
  "Flores",
  "Floresta",
  "La Boca",
  "La Paternal",
  "Liniers",
  "Mataderos",
  "Monte Castro",
  "Montserrat",
  "Nueva Pompeya",
  "Núñez",
  "Palermo",
  "Parque Avellaneda",
  "Parque Chacabuco",
  "Parque Chas",
  "Parque Patricios",
  "Puerto Madero",
  "Recoleta",
  "Retiro",
  "Saavedra",
  "San Cristóbal",
  "San Nicolás",
  "San Telmo",
  "Versalles",
  "Villa Crespo",
  "Villa del Parque",
  "Villa Devoto",
  "Villa General Mitre",
  "Villa Lugano",
  "Villa Luro",
  "Villa Ortúzar",
  "Villa Pueyrredón",
  "Villa Real",
  "Villa Riachuelo",
  "Villa Santa Rita",
  "Villa Soldati",
  "Villa Urquiza",
  "Vélez Sársfield",
];

export const PARTIDOS_PBA: string[] = [
  // GBA Norte
  "Campana",
  "Escobar",
  "Exaltación de la Cruz",
  "Pilar",
  "San Fernando",
  "San Isidro",
  "Tigre",
  "Vicente López",
  "Zárate",
  // GBA Noroeste
  "Hurlingham",
  "Ituzaingó",
  "José C. Paz",
  "Malvinas Argentinas",
  "Moreno",
  "Morón",
  "San Martín",
  "Tres de Febrero",
  // GBA Oeste
  "La Matanza",
  "Luján",
  "Marcos Paz",
  "Mercedes",
  "Merlo",
  "Navarro",
  // GBA Sur
  "Almirante Brown",
  "Avellaneda",
  "Berazategui",
  "Esteban Echeverría",
  "Ezeiza",
  "Florencio Varela",
  "Lanús",
  "Lomas de Zamora",
  "Presidente Perón",
  "Quilmes",
  "San Vicente",
  // Interior — Region Bonaerense
  "Adolfo Alsina",
  "Adolfo Gonzales Chaves",
  "Alberti",
  "Arrecifes",
  "Ayacucho",
  "Azul",
  "Bahía Blanca",
  "Balcarce",
  "Baradero",
  "Benito Juárez",
  "Berisso",
  "Bolívar",
  "Brandsen",
  "Bragado",
  "Carmen de Areco",
  "Castelli",
  "Cañuelas",
  "Chascomús",
  "Chivilcoy",
  "Colón",
  "Coronel Dorrego",
  "Coronel Pringles",
  "Coronel Rosales",
  "Coronel Suárez",
  "Daireaux",
  "Dolores",
  "Ensenada",
  "Florentino Ameghino",
  "General Alvarado",
  "General Alvear",
  "General Arenales",
  "General Belgrano",
  "General Guido",
  "General Juan Madariaga",
  "General La Madrid",
  "General Las Heras",
  "General Lavalle",
  "General Paz",
  "General Pinto",
  "General Pueyrredón",
  "General Rodríguez",
  "General San Martín",
  "General Viamonte",
  "General Villegas",
  "Guaminí",
  "Hipólito Yrigoyen",
  "Junín",
  "La Costa",
  "La Plata",
  "Laprida",
  "Las Flores",
  "Leandro N. Alem",
  "Lincoln",
  "Lobería",
  "Lobos",
  "Lezama",
  "Maipú",
  "Mar Chiquita",
  "Magdalena",
  "Monte",
  "Monte Hermoso",
  "Necochea",
  "Nueve de Julio",
  "Olavarría",
  "Patagones",
  "Pehuajó",
  "Pellegrini",
  "Pergamino",
  "Pinamar",
  "Puan",
  "Punta Indio",
  "Ramallo",
  "Rauch",
  "Rivadavia",
  "Rojas",
  "Roque Pérez",
  "Saavedra",
  "Saladillo",
  "Salliqueló",
  "Salto",
  "San Andrés de Giles",
  "San Antonio de Areco",
  "San Cayetano",
  "San Nicolás",
  "San Pedro",
  "Suipacha",
  "Tandil",
  "Tapalqué",
  "Tordillo",
  "Tornquist",
  "Trenque Lauquen",
  "Tres Arroyos",
  "Tres Lomas",
  "Veinticinco de Mayo",
  "Villa Gesell",
  "Villarino",
];

export const UBICACIONES: Record<Zona, string[]> = {
  "Ciudad Autónoma de Buenos Aires": BARRIOS_CABA,
  "Provincia de Buenos Aires": PARTIDOS_PBA,
};

export function slugifyUbicacion(str: string): string {
  return str
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");
}
